require("config")
require("keymaps")
require("plugins/catppuccin")
require("plugins/plenary")
require("plugins/mini-icons")
-- require("plugins/oil")
require("plugins/lsp")
require("plugins/completions")
require("plugins/mini-pairs")
require("plugins/formatter")
require("plugins/diagnostics")
require("plugins/nvim-surround")
require("plugins/picker")
require("plugins/files")
require("plugins/which-key")
require("plugins/tiny-code-action")
require("plugins/fidget")
require("plugins/codecompanion")
require("plugins/treesitter")
require("plugins/flash")
require("plugins/grug-far")
require("plugins/messages")
-- require("plugins/fff")
require("plugins/sql")
require("plugins/undotree")
require("plugins/illuminate")
require("plugins/urls")
