lastChangelogVersion: 13.12.3
modelRoles: 
  default: openai-codex/gpt-5.4:high
  plan: openai-codex/gpt-5.4:high
  slow: zai/glm-5:high
  smol: minimax-code/MiniMax-M2.5-lightning:high
  commit: openai-codex/gpt-5.3-codex
providers: 
  webSearch: kagi
lsp: 
  formatOnWrite: true
  diagnosticsOnEdit: true
memories: 
  enabled: true
ask: 
  timeout: 0
astEdit: 
  enabled: false
todo: 
  reminders: false