# theme = "catppuccin_mocha"

[editor]
line-number = "relative"
end-of-line-diagnostics = "hint"
popup-border = "all"

[editor.statusline]
right = ["file-type", "diagnostics", "selections", "register", "position", "file-encoding"]
separator = "│"

[editor.cursor-shape]
insert = "bar"
normal = "block"
select = "underline"

[editor.file-picker]
hidden = false

[editor.soft-wrap]
enable = true

[editor.lsp]
display-messages = true

[editor.inline-diagnostics]
cursor-line = "hint"

[keys.normal]
C-h = "jump_view_left"
C-l = "jump_view_right"
C-j = "jump_view_down"
C-k = "jump_view_up"
