[[language]]
name = "rust"
formatter = { command = "rustfmt" , args = ["+nightly"] }

[language-server.rust-analyzer.config]
cargo.features = "all"
check.command = "clippy"
# inlayHints.typeHints.enable = false
# inlayHints.parameterHints.enable = false
# inlayHints.chainingHints.enable = false
