[terminal]
shell = "nu"

[font]
normal.family = "FiraCode Nerd Font"
normal.style = "Semibold"
size = 10

[cursor.style]
blinking = "Always"
shape = "Block"

[window]
option_as_alt = "Both"

[keyboard]
bindings = [
	{ key = "M", mods = "Control", action = "CreateNewWindow" }
]
